name: Deploy Firebase Functions
on:
  push:
    branches: [ main ]
    paths: [ 'functions/**' ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache-dependency-path: functions/package.json
      - name: Install dependencies
        working-directory: ./functions
        run: npm install
      - name: Deploy
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions --project controle-financeiro-e4f3b
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
